= Designing software

== Determine the goal of the software

Example:

Typically, in pharma/biotech companies there's no visibility about who does what with which compounds.
The teams and people could be duplicating efforts and nobody will notice that.

Additionally, the software systems are often disconnected, and if we're doing something in AppA and need information
from AppB, the user has to manually go and search for that info. Since scientists often need info from many systems,
this makes data gathering very time-consuming.

== Envision typical use

This format of describing the requirements/use cases is called User Stories:

. As a scientist, when drawing a compound in my ELN (or other software), I'd like to automatically see if someone has
already done anything of interest with it (e.g. already synthesized it) so that I don't repeat the work.
. As a team leader, I'd like to see the progress on the compound that we discussed during our last meeting, so
that I could coordinate the next steps.
. As a manager, I'd like to see the steps taken by different teams to work on the compounds (together with the stats
like how much time the team worked on a compound, or the delay between steps). So that I see the bottlenecks and
determine which steps of the process should be optimized first.

== How the new software will help

The new software is going to represent a database of everything useful happening to the compounds. We'll write
scripts to periodically (or actively) loading the data from all interesting data sources.

Different step of the process (e.g. compare Synthesis vs Bioassay) provides very different information. So to provide
a unified way of storing it, we treat everything as Events (e.g. a compound was PURIFIED - it's an event):

* Compound info (structure, ID, pic) is common for all the events
* Events will have common attributes: timestamps, user, etc.
* The event-specified attributes are stored in JSON
* Each event references a system the data came from: URL to the user-friendly info from that system, as well as an
API URL for programmatic access. This way if the summary that's stored in the event isn't enough, at least user can
follow the links to quickly find the rest.