= ID Generation strategies in databases

Each row in a table is usually identified by some unique attribute(s) - a key. Tables reference each other using
these keys. Often there are multiple unique attributes to choose from (like user email or social number). But we
rarely use those, so called, "natural" keys:

* The laws and regulations change. What was considered mandatory and/or unique today, will become optional (e.g.
  you can exempt from SSN) or recyclable (e.g. once a contract with a phone company is terminated, the phone
  number is returned back to the pool and later will be resold).
* The business rules evolve. Today you may think that username is required, tomorrow you'll ask user only for the email.
* Some attributes, while unique, may become mutable. E.g. email is unique and can identify a person, but people have
  many emails and may want to change them in the future.

If the natural key becomes non-unique or if it's mutable, we're in trouble:

* If 10 other tables referenced a key that was updated, we have to update 10 tables
* But even worse - what if we put a link to some page in an email or in documentation? If the ID changes, the link
becomes broken. And there's no way to learn this and/or update it everywhere.

This is why most of the time we use so-called "surrogate" keys. They are generated programmatically
(instead of being entered), and they don't have any meaning or any other role besides identifying a row.

There 2 popular ways of generating surrogate keys: UUID and Sequence generators.

== UUID (aka GUID)

UUID is a globally unique identifier. It's basically an array of bytes, but often it's presented as hex string like
this: `123e4567-e89b-12d3-a456-426614174000`.

How do we generate it? There are functions inside a DB that can do this, or we can do this on the app side -
every programming environment has functions for this.

There are different flavors aka https://www.rfc-editor.org/rfc/rfc9562.html[versions of UUID]s: some of them are
completely random, some depend on the computer hardware, etc.

Most UUID versions don't have any order - the next generated value could be "smaller" than the previous one. If you use
Postgres https://www.postgresql.org/docs/current/functions-uuid.html[UUID()], you're in this situation. This is
unfortunate:

* Sorting records by the order of their insertion is quite a common use case. And if the ID isn't ordered, we can't
sort by it.
* We often query related objects that were created together or soon after one another. Ideally, those records are
located close to each other on disk and in memory (we call this Data Locality). This way the DB can read a single
page of data with many relevant records, as opposed to reading many pages with only 1 relevant record at a time.
But if the IDs doesn't correlate with the insertion time, at least some of the data will be scattered around.
We'll cover this topic in more detail later.

So we either need to rely on UUIDv1 (time-based, ordered) or rely on other attributes (like an explicit `insert_time`)
for sorting.

== Sequences

Sequence are counters that the database remembers. When you generate a new value, the counter is incremented
and the next time it will generate a bigger value. This guarantees a monotonically increasing ID, which is great.

You can share a Sequence between tables in which case your ID will be unique across all those tables. Or you can
create a Sequence-per-table in which case every type of your entities will start with 1 and so on. The latter is
more popular.

Some downsides of the sequences:

* You need a database or some other single point to generate them. While the UUID can be generated right in the app
code.
* They are the source of contention - if multiple threads/processes access the same counter, they'll have to wait
for each other.
* They are number-based, and can overflow after 2 billion values if `int4` is used instead of `int8`
* They can't be easily distributed. So if you use a distributed database (which we won't consider here), how do you
generate a common counter and be fast? This is a huge problem, that can't be solved perfectly.

== Automatically generated IDs

You can explicitly generate the ID using the app logic/database functions during your `INSERT`s.

Alternatively, you can ask the database to do this automatically:

[source, sql]
----
create table t1 (id integer primary key generated by default as identity);
----